openapi: 3.0.4
info:
  title: Marketplace
  description: This is a place where sellers and buyers meat each other
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost/v1
tags:
  - name: ad
    description: Объвление (о покупке или продаже)
  - name: pet
    description: Everything about your Pets
paths:
  /ad/create:
    post:
      tags:
        - ad
      summary: Create ad
      operationId: adCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdCreateResponse'
  /ad/read:
    post:
      tags:
        - ad
      summary: Read ad
      operationId: adRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdReadResponse'
  /ad/update:
    post:
      tags:
        - ad
      summary: Update ad
      operationId: adUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdUpdateResponse'
  /ad/delete:
    post:
      tags:
        - ad
      summary: Delete ad
      operationId: adDelete
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdDeleteRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDeleteResponse'
  /ad/search:
    post:
      tags:
        - ad
      summary: Update ad
      operationId: adSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdSearchResponse'
  /ad/offers:
    post:
      tags:
        - ad
      summary: Update ad
      operationId: adOffers
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdOffersRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdOffersResponse'

components:
  schemas:

    RequestDebug:
      type: object
      properties:
        mode:
          type: string
          enum:
            - prod
            - test
            - stub
        stub:
          type: string
          description: 'Тип стаба, который запрашиваем в режиме mode: stub'
          enum:
            - success

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        requestId:
          type: string
          description: Идентификатор запроса для отладки
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/AdCreateRequest'
          read:   '#/components/schemas/AdReadRequest'
          update: '#/components/schemas/AdUpdateRequest'
          delete: '#/components/schemas/AdDeleteRequest'
          search: '#/components/schemas/AdSearchRequest'
          offers: '#/components/schemas/AdOffersRequest'

    Error:
      type: object
      properties:
        code:
          type: string
        groupd:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        responseType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        requestId:
          type: string
          description: Идентификатор запроса для отладки
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/AdCreateResponse'
          read:   '#/components/schemas/AdReadResponse'
          update: '#/components/schemas/AdUpdateResponse'
          delete: '#/components/schemas/AdDeleteResponse'
          search: '#/components/schemas/AdSearchResponse'
          offers: '#/components/schemas/AdOffersResponse'


    DealSide:
      type: string
      description: 'Сторона сделки: объявление о продаже или о покупке'
      enum:
        - demand
        - proposal

    IAdProduct:
      type: object
      properties:
        productType:
          type: string
          description: Свойство для дескриминатора, описывающее тип товара
      discriminator:
        propertyName: productType
        mapping:
          bolt: '#/components/schemas/AdProductBolt'

    AdProductBolt:
      allOf:
        - $ref: '#/components/schemas/IAdProduct'
        - type: object
          description: 'Объявление, описывающее болт'
          properties:
            length:
              type: number
              format: double
              description: Длина болта
            diameter:
              type: number
              format: double
              description: Диаметр болта
            headStyle:
              type: string
              description: Тип шляпки
              enum:
                - squareShoulder
                - indentedHexagon
                - indentedHexagonWasher
                - hexagonFlange
            thread:
              type: object
              description: Резьба
              properties:
                pitch:
                  type: number
                  format: double
                  description: 'Размер резьбы: расстояние между бороздами'
                pitchConf:
                  type: string
                  description: 'Тип резьбы: грубая, мелкая'
                  enum:
                    - coarse
                    - fine

    AdVisibility:
      type: string
      description: 'Тип видимости объявления. Возможные значения: видит только владелец, только зарегистрированный в системе пользователь, видимо всем'
      enum:
        - ownerOnly
        - registeredOnly
        - public

    BaseAdUpdateable:
      type: object
      description: Объект описывает свойства, одинаковые для create и update
      properties:
        title:
          type: string
          description: Заголовок объявления
        description:
          type: string
          description: Описание объявления
        ownerId:
          type: string
          description: Идентификатор владельца объявления
        adType:
          $ref: '#/components/schemas/DealSide'
        visibility:
          $ref: '#/components/schemas/AdVisibility'
        props:
          $ref: '#/components/schemas/IAdProduct'


    BaseAdUpdateableRequest:
      allOf:
        - type: object
          properties:
            ad:
              $ref: '#/components/schemas/BaseAdUpdateable'
            debug:
              $ref: '#/components/schemas/RequestDebug'

    BaseAdIdRequest:
      type: object
      properties:
        ad:
          allOf:
              - $ref: '#/components/schemas/BaseWithId'
        debug:
          type: object
          properties:
            stub:
              type: string
              enum:
                - success
                - notFound
                - badId

    BaseWithId:
      type: object
      properties:
        ad:
          type: object
          properties:
            id:
              type: string
              description: Идентификатор объявления

    AdCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BaseAdUpdateableRequest'

    AdReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BaseAdIdRequest'

    AdUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BaseAdUpdateableRequest'
        - type: object
          properties:
            ad:
              allOf:
                - $ref: '#/components/schemas/BaseWithId'

    AdDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BaseAdIdRequest'
        - type: object
          properties:
            stub:
              type: string
              enum:
                - cannotDelete

    AdSearchFilter:
      type: object
      description: Набор фильтров для поиска
      properties:
        searchString:
          type: string
          description: Поисковая строка, которая будет искаться в объявлениях

    AdSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            adFileter:
              $ref: '#/components/schemas/AdSearchFilter'

    AdOffersRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BaseAdIdRequest'

    AdPermissions:
      type: string
      description: Доступы для клиента для операций над объявлением
      enum:
        - read
        - update
        - delete
        - makeVisiblePublic
        - makeVisibleOwn
        - makeVisibleGroup

    AdResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseWithId'
        - $ref: '#/components/schemas/BaseAdUpdateable'
        - type: object
          description: Объект, который возвращается в ответе бэкенда
          properties:
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/AdPermissions'

    AdResponseSingle:
      allOf:
        - $ref: '#/components/schemas/BaseAdUpdateableRequest'
        - type: object
          description: Ответ с одним объектом объявления
          properties:
            ad:
              $ref: '#/components/schemas/AdResponseObject'


    AdCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - type: object
          description: Список найденных объектов
          properties:
            ads:
              type: array
              items:
                $ref: '#/components/schemas/AdResponseObject'

    AdOffersResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'
        - type: object
          description: Список найденных объектов
          properties:
            offers:
              type: array
              items:
                $ref: '#/components/schemas/AdResponseObject'
